# Generated by Django 5.2 on 2025-04-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('RAP', 'Rap'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
