# Generated by Django 5.2 on 2025-04-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumbox', '0002_remove_artist_origin_country_remove_track_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/albums/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/artists/'),
        ),
    ]
