# Generated by Django 5.2 on 2025-04-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumbox', '0003_alter_album_picture_alter_artist_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
