# Generated by Django 5.2 on 2025-04-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumbox', '0008_alter_artist_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_genre',
            field=models.CharField(blank=True, choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('RAP', 'Rap'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('RAP', 'Rap'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
