# Generated by Django 5.1.6 on 2025-03-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumDetails',
            fields=[
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='musicApp.album')),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True)),
                ('major', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('albums', models.ManyToManyField(to='musicApp.album')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('duration', models.CharField(max_length=20)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicApp.album')),
            ],
        ),
    ]
